project:
  type: website

website:
  title: "Website"
  favicon: "images/dionne_cartoon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: twitter
        href: https://twitter.com/DionneArgy
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/dionnecargy
          - text: Report a Bug
            url:  https://github.com/dionnecargy
    search: false
  page-footer: 
    left: "Copyright 2024, Dionne C. Argyropoulos"
    right: 
      - icon: github
        href: https://github.com/dionnecargy
      - icon: twitter
        href: https://twitter.com/DionneArgy
  page-navigation: true
  back-to-top-navigation: true
  sidebar:
    style: "docked"
    search: true
    logo: "images/dionne_cartoon.png"
    contents:
      - index.qmd
      # - section: "Research"
      #   contents: 
      #     - "Pages_CV/03_ResearchInterests.qmd"
      #     - "Pages_CV/04_PublishedPapers.qmd"
      #     - "Pages_CV/05_Conferences.qmd"
      # - section: "Leadership, Community and Engagement"
      #   contents: 
      #     - "Pages_CV/06_Volunteering.qmd"
      #     - "Pages_CV/07_Awards.qmd"
      #     - "Pages_CV/08_Work.qmd"
      - section: "Code: The Basics"
        contents: 
          - "code/00_code_intro.qmd"
          - "code/01_quarto.qmd"
          - "code/02_package.qmd"
          - "code/03_shiny.qmd"
          - "code/04_targets.qmd"

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.css]
    css: styles.css
    code-overflow: wrap
    toc: true
    execute:
      warning: false

editor: visual

